# Config File
name: "mace_50_training"
foundation_model: "large"
model: "MACE"
E0s: "{1:-13.656315639066156, 6:-146.65071522867848, 8:-432.2257363227328}"
model_dir: "MACE_models"
log_dir: "MACE_models"
checkpoints_dir: "MACE_models"
results_dir: "MACE_Train_Results"
train_file: "/home/CRSid/rds/hpc-work/written_assignment_2/train_validation_test_sets/bulk_and_confined_datasets_training_50/train_50_structures.xyz"
valid_file: "/home/CRSid/rds/hpc-work/written_assignment_2/train_validation_test_sets/bulk_and_confined_datasets_training_50/val_100_structures.xyz"
test_file: "/home/CRSid/rds/hpc-work/written_assignment_2/train_validation_test_sets/bulk_and_confined_datasets_training_50/test_500_structures.xyz"
energy_key: "REF_energy"
forces_key: "REF_forces"
pt_train_file: "mp"
device: cuda
swa: True
default_dtype: "float64"

batch_size: 2
max_num_epochs: 110
patience: 10
eval_interval: 5
valid_batch_size: 2

amsgrad: True
ema: True
ema_decay: 0.99
lr: 0.01
max_L: 3
r_max: 3.0

correlation: 3

stress_weight: 0.0
forces_weight: 10.0
energy_weight: 1.0

restart_latest: True
seed: 3
